### ISSUE TITLE
Fix Western Sahara bug

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#192]
For example seen here: https://github.com/oscovida/oscovida/runs/1498418948#step:6:646

This blocks current pull requests.

**Comment by kirienko** [comment]
Samoa was fixed on its own, while Western Sahara is a new one.
It is related to the last Trump's decision to name Western Sahara as a part of Morocco. Technically the changes are due to [this issue](https://github.com/CSSEGISandData/COVID-19/issues/3436).

**Comment by fangohr** [comment]
Good working finding the origin. It sounds like this error will not disappear over time?

Should we adapt the test(s) to pass then if only Western Sahara shows up as a problem?

**Comment by kirienko** [comment]
Yes, exactly: the error will persist until the guys gain the independence. Fixing the tests is quite an easy solution, and that's what I've done. Though ideally we could sanitise our data by removing `Western Sahara` from the beginning. Otherwise the country page will be created every time but never receive any updates after some Dec 2020.
