### ISSUE TITLE
Codebase on binder seems not to be up-to-date

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#215]
After the merge that includes the running 7-day incidence, the code that is used on Binder does not contain that change yet (still shows the total infections and deaths in log scale in plot one).

**Comment by RobertRosca** [comment]
Took me a while to get to this, and then misunderstood what the problem was for a bit :sweat_smile: 

https://github.com/oscovida/binder/blob/master/requirements.txt

Binder uses the latest release version from pypi. Setting it to just use master isn't good since binder won't update on changes, setting it to clone the whole repo and keep it there is also not the best option if you're just pip installing from the directory.

It's a bit silly but now my solution is to add the latest master hash to the requirements file as part of the CI, this way it'll be updated when changes have been merged to master automatically.

**Comment by RobertRosca** [comment]
With https://github.com/oscovida/binder/pull/8 this is fixed now
