### ISSUE TITLE
Plots for Germany have wrong shape

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#70]
Strange shape of axes in plots for Germany. All landkreise seem affected, for example https://oscovida.github.io/html/Germany-Nordrhein-Westfalen-LK-Gütersloh.html

<img width="1175" alt="Screenshot 2020-07-04 at 14 22 34" src="https://user-images.githubusercontent.com/4489119/86512366-d968f300-be01-11ea-964d-155ef305e12b.png">

[I submitted an issue for this yesterday night, but couldn't find it now; maybe something went wrong with the upload.]

**Comment by RobertRosca** [comment]
Last time this was working was Friday 03/07/2020 AM: https://htmlpreview.github.io/?https://github.com/oscovida/oscovida.github.io/blob/0ffcd358db7144bb7db4dc1893e15528b50a03c9/html/Germany-Baden-W%C3%BCrttemberg-LK-Alb-Donau-Kreis.html

Broke Friday 03/07/2020 PM https://htmlpreview.github.io/?https://github.com/oscovida/oscovida.github.io/blob/4669bb434a24f1103df0a88019c69e9524216e73/html/Germany-Baden-W%C3%BCrttemberg-LK-Alb-Donau-Kreis.html

Must be due to a change introduced from the Hungarian data integration. I'll look into it today if I have time or tomorrow.

**Comment by RobertRosca** [comment]
4d2b3befa3c6148a643aade971d34877d3d5daa7 fixes this issue.
